python adaptation.py \
    --model_name kitti2dgp_ssl_naive \
    --dataset dgp \
    --load_weights_folder ./exp_logs/kitti_sup/models/weights_19 \
    --models_to_load encoder depth \
    --reg_path ./exp_logs/kitti_unsup/models/weights_19 \
    --thres 0.4 \
    --num_workers 0 \
    --data_path /datasets/ddad_train_val \
    --adaptation_method ssl_naive \
    --learning_rate 1e-5 \
    --single_img_experiment \
    --skip_layers \
    --frame_ids 0 -1
